### ISSUE TITLE
`GlobalWorkerOptions.workerSrc` points to a CDN

### ISSUE THREAD

**Issue by lazylace37** [pdfslick/pdfslick#30]
Hi!

I noticed that `GlobalWorkerOptions.workerSrc` points to `cdn.jsdelivr.net` by default, and there's no way to change that from the outside.

https://github.com/pdfslick/pdfslick/blob/5abacb3d3b281f7743fedbd7f07d766638499522/packages/core/PDFSlick.ts#L53

But I also noticed there's already a `pdf.worker.js` in `core/lib/`.  
Do you think we can fix this?  
Thanks

**Comment by van100j** [comment]
I guess we can give it another try. I remember having issues with importing it locally the last time I've tried, so I went with loading it from the CDN.

**Comment by lazylace37** [comment]
I'm happy to help!

The only thing is I don't know how to test it locally... If I run `npm run dev` I can bring up the example apps, but when I make a change to the `core/` package, it doesn't seem to update them.

**Comment by van100j** [comment]
@lazylace37 How exactly are you testing it locally? See changing the worker URL and auto-updating the example app in the screencast below.

https://github.com/pdfslick/pdfslick/assets/408278/c1d1c68c-663a-41f8-9290-586d4c9d3007

**Comment by van100j** [comment]
* Added local PDF.js worker in #31
