### ISSUE TITLE
How to get annotations/forms working in Svelte?

### ISSUE THREAD

**Issue by martinjo** [pdfslick/pdfslick#35]
I've tried using your library in my sveltekit application and I can get my PDF loading and showing up. I have a few questions though.

- How can I get forms in the PDF to render (allowing for interactions)?
- How can I set the actual viewport of the pdf renderer? Using the example it takes up the whole screen, and it seems to break as soon as I try to modify the layout. Do you have any examples or pointers as to where I can look?

Thanks!

**Comment by van100j** [comment]
Hi @martinjo

PDFSlick is a layer atop [PDF.js](https://github.com/mozilla/pdf.js) and should render forms by default. It also renders in an absolute container so it adjusts to whatever parent you put it in.

Specifically for Svelte, [here's an example](https://github.com/pdfslick/pdfslick/blob/main/apps/svelteweb/src/routes/custom-viewport/%2Bpage.svelte) with a viewport  with custom width and height, and also showcasing a PDF with interactive forms — a screencast of this demo available at https://www.loom.com/share/77c4241fafd146bf9d75a2edc5a5ddc9

**Comment by martinjo** [comment]
Wow, thanks! 🙏 That worked perfectly :). I had missed importing the css-file and that made the annotation/form overlay render completely off. 

Another thing I noticed is that when I load a new document after another file has already been loaded, then the pages will stack under the pages of the previous file. I solved it with a {#key} statement on the container, but it feels off.  Am I supposed to do something before/after loading a new file?

**Comment by van100j** [comment]
Yep, I can also see this happening when uploading a new doc. For some reason [`#hiddenCopyElement` is not removed on `_resetView()`](https://github.com/mozilla/pdf.js/blob/v3.11.174/web/pdf_viewer.js#L1096), will need to figure out why.

In the meantime I guess you can either use your current fix with `{#key}`, or you can [manually remove `#hiddenCopyElement`](https://github.com/pdfslick/pdfslick/blob/main/apps/svelteweb/src/routes/custom-viewport/%2Bpage.svelte#L41) before loading a new pdf document as pdf.js does when loading a new doc.

**Comment by martinjo** [comment]
Ok! That is perhaps a more nimble solution. Thanks :)

I'll close this now. Will open a new issue if I find any...
