### ISSUE TITLE
onError callback

### ISSUE THREAD

**Issue by meseven** [pdfslick/pdfslick#39]
Hello,
I want to use this library in my React project, but I couldn't figure out how to catch an error when loading a document. 

Does this library provide a callback that allows us to catch errors?

**Comment by van100j** [comment]
Hi @meseven !

Support for error handling has been added in version `1.5.0`.

Specifically for React take a look at the [error handling example](https://github.com/pdfslick/pdfslick/blob/main/apps/web/examples/ErrorHandling.tsx), for which a [demo](https://pdfslick.dev/examples/error-handling) is also available.

**Comment by meseven** [comment]
It's great! Thank you very much.
So with this update, can we run a callback function like below?

```javascript
const { viewerRef, usePDFSlickStore, PDFSlickViewer, error } = usePDFSlick(
  pdfFilePath,
  {
    onError: (error) => {
      console.log(error);
    }
  }
);
```

**Comment by van100j** [comment]
No, with `usePDFSlick` hook you can use the returned `error` when loading a PDF document to detect and act upon errors.

If you want to use the `onError` callback consider using PDFSlick's core package — see the [Svelte example](https://github.com/pdfslick/pdfslick/blob/main/apps/svelteweb/src/routes/error-handling/%2Bpage.svelte#L32) for reference.

**Comment by meseven** [comment]
Thanks a lot @van100j.
