### ISSUE TITLE
unformatted text in viewer, when going to examples from GitHub

### ISSUE THREAD

**Issue by smundro** [pdfslick/pdfslick#42]
First view of examples worked fine, but going to github and following the link to the examples resulted in unformatted text displayed in the viewer.  Reload fixed the issue, going to github back to examples exposed the issue again.  Firefox 127 on Mac, not reproducible in Chrome / Safari.
 
<img width="1028" alt="image" src="https://github.com/pdfslick/pdfslick/assets/1800645/aa6cb473-0fc2-48e3-ad09-e137907969d2">

**Comment by van100j** [comment]
Thanks @smundro! Will take a look.

**Comment by van100j** [comment]
Solved in #58
