### ISSUE TITLE
Minor documentation change

### ISSUE THREAD

**Issue by m4nh** [pdfslick/pdfslick#46]
In your `Svelte` Getting Started guide: https://pdfslick.dev/docs/svelte there is a minor error:

```
import "@pdfslick/solid/dist/pdf_viewer.css";
```

Should be:

```
import '@pdfslick/core/dist/pdf_viewer.css';
```

Just to avoid Svelte user to download the *solid* version.
Sorry if I'm being a pain in the ass :)

**Comment by van100j** [comment]
Hey @m4nh, thanks for noticing and sharing this. You're totally not being pain the ass :)

Cheers!
