### ISSUE TITLE
Reactjs - PDF Layout broken

### ISSUE THREAD

**Issue by swotiendang** [pdfslick/pdfslick#52]
From latest chrome version v129 and latest window 11 version 23H2
Link: https://pdfslick.dev/examples/simple-pdf-viewer

This issue sometimes happen, especially first open after a while

Expected:
![image](https://github.com/user-attachments/assets/a3058234-bae4-488a-854d-1cda1d718497)

Actual: 
![2024-10-07_231128](https://github.com/user-attachments/assets/49ccdd98-058c-4268-b78f-6a2ef377b77f)
![2024-10-07_231136](https://github.com/user-attachments/assets/8c8918aa-db87-43e9-bfab-6d4e8cb62442)
![image](https://github.com/user-attachments/assets/0f641809-f20a-424c-bc60-8fd9128a023c)

I found this issue happen in https://pdfslick.dev/examples/pdf-viewer-app and https://pdfslick.dev/examples/simple-pdf-viewer

Abnormal behavior:
CSS went weird:
Expected:
![2024-10-08_170431](https://github.com/user-attachments/assets/eadfa651-02ee-418b-aad0-b690fe6f7d28)
Actual:
![2024-10-08_170449](https://github.com/user-attachments/assets/c812b3f9-fbdb-488d-8a01-2b018c1d1e44)

**Comment by swotiendang** [comment]
Hi @van100j  this is intermittent issue, from this page: https://pdfslick.dev/examples, sometimes click to anypage will have this issue, but reloading the page resolves it.
It happens because you can see pdf_viewer.css is missing from the page 
![image](https://github.com/user-attachments/assets/a9c646d4-dd4d-4420-9f2a-ca3a78c1de89)

It might be Nextjs issue that we need to config cssLoader
https://stackoverflow.com/a/74968963/15538104

This is the issue with landing page only, core pdfslick is good, appreciate your work.

**Comment by swotiendang** [comment]
Same case as #42

**Comment by van100j** [comment]
So adding the [styles in `globals.css`](https://github.com/pdfslick/pdfslick/pull/53/files#diff-64107133be272585500a4779164ef29b57e0d89d244ee7a13cb873cb77a0b382R12) solves this, correct?

**Comment by swotiendang** [comment]
@van100j  from my observation, yes.

**Comment by van100j** [comment]
Solved in #58
