### ISSUE TITLE
Reactjs - PDF Forms Input Bug

### ISSUE THREAD

**Issue by guptabhaskar** [pdfslick/pdfslick#57]
**All the inputs come on the first page, that's why we see a lot of overlapping and random inputs.
It works sometimes, but not sure what causes it.**

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/05043fb3-b09f-4198-b3d3-3222905a710a">

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by guptabhaskar** [comment]
@van100j you can download it from here: https://www.uscis.gov/sites/default/files/document/forms/i-129.pdf

**Comment by van100j** [comment]
@guptabhaskar it's properly showing PDF with forms but the example was messed up when loading new PDF files.

[The PDF Viewr App example is fixed now](https://pdfslick.dev/examples/pdf-viewer-app?pdf=/pdfs/i-129.pdf) (or also [created a separate app with the PDF form loaded by default](https://pdfslick.dev/examples/pdf-viewer-app-with-form))
