### ISSUE TITLE
PDF Randomly Renders with Black Pages

### ISSUE THREAD

**Issue by ConProgramming** [pdfslick/pdfslick#63]
This seems to happen randomly, and pretty rarely but often enough to be annoying. The same PDF which usually renders fine will sometimes render with black pages. What could be causing this?

<img width="463" alt="Black" src="https://github.com/user-attachments/assets/048efdd5-3a79-474a-bda9-27b89bcab7eb">
<img width="463" alt="Normal" src="https://github.com/user-attachments/assets/557ddf05-ec4a-4293-b455-19a153d4bd1a">

**Comment by van100j** [comment]
Hi @ConProgramming

Hard to say without more details, but if your app uses light/dark themes, I'd check whether they're interfering with pdf.js's CSS styles.

**Comment by ConProgramming** [comment]
> Hi @ConProgramming
> 
> 
> 
> Hard to say without more details, but if your app uses light/dark themes, I'd check whether they're interfering with pdf.js's CSS styles.

Thanks for the response @van100j. It only happens on dark themes, but it seems to be random and pretty rare. It also always goes away on refresh. Is there some parameter I can pass that forces pdf.js to stay light theme?

I looked online and saw some notes of pdf.js having a built in dark theme but I couldn't find how to force it to stay disabled.

**Comment by van100j** [comment]
@ConProgramming can you poke around, inspect elements in developers tools to see if any of pdf.js CSS vars gets through or how the dark bg colors and light text colors get applied? If possible share a link, I'd take a look too.

**Comment by ConProgramming** [comment]
<img width="432" alt="Screenshot 2024-12-14 at 2 09 13 AM" src="https://github.com/user-attachments/assets/7a6cd362-7137-4404-b1b8-999378dbdbf1" />
@van100j I managed to find the source of the CSS - it's a filter being applied directly on the canvas.

On closer inspection, this CSS was bleeding in from another Svelte component. Sorry about this, thanks for the help!
